[book]
title = "Build Your Own ESP32 Computer — A KiCad PCB Design Handbook"
authors = ["Pa3cio, UL FRI"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
additional-css = ["fri.css"]
# git-repository-url = "https://github.com/bulicp/FRI-ESP32-PCB-workshop"
